spers:
    ficture:
        cosmx:
            mu_scale: 8
            headers:
                x: x_global_px
                y: y_global_px
                gene: target
            gene_filter: "SystemControl"
        xenium:
            mu_scale: 1
            headers:
                transcript_id: transcript_id
                x: x_location
                y: y_location
                gene: feature_name
            gene_filter: "Control|Neg|Unassigned"
        minibatch:
            batch_size: 500
            batch_buff: 30
        coarse_hex:
            hex_width: 12
            min_transcripts_per_hex: 50
            min_transcripts_per_gene: 50
            min_transcripts_per_minibatch: 50
        coarse_model:
            test_split: 0.5
            generate_models: 5
            output_models: 5
            random_state: 555
            min_transcripts_scored: 50
            lda:
                n_components: 12
                learning_method: online
                batch_size: 512
                learning_offset: 9
                learning_decay: 0.7
                doc_topic_prior: 1
        coarse_plot:
            transcripts_per_hex: 10
            palette: dark
            background: white
            microns_per_inch: 150
            point_scale: 2.5
            font_scale: 5
        transcript_score:
            hex_width: 12
            offset_steps: [ -2, -1, 0, 1, 2]
            step_size: 4
        transcript_plot:
            hex_width: 12
            min_transcripts_per_hex: 0
            transcripts_per_hex: 100
            palette: dark
            background: white
            microns_per_inch: 50
            point_scale: 1
            font_scale: 5
    resources:
        big:
            mem: "64G"
            cpu: 32
            time: "24:00:00"
        med:
            mem: "16G"
            cpu: 8
            time: "04:00:00"
        sml:
            mem: "2G"
            cpu: 1
            time: "01:00:00"
        ram:
            mem: "16G"
            cpu: 2
            time: "04:00:00"