spers:
    ficture:
        cosmx:
            mu_scale: 8
            headers:
                x: x_global_px
                y: y_global_px
                gene: target
            gene_filter: "SystemControl"
        xenium:
            mu_scale: 1
            headers:
                transcript_id: transcript_id
                x: x_location
                y: y_location
                gene: feature_name
            gene_filter: "Control|Neg|Unassigned"
        lda_model:
            random_state: 555
            bin:
                hex_width: 16
                batch_size: 500
                batch_buff: 30
                min_transcripts_per_hex: 50
                min_transcripts_per_gene: 50
                min_transcripts_per_minibatch: 50
            train:
                test_split: 0.5
                generate_models: 5
                output_models: 5
                min_transcripts_scored: 50
            lda:
                n_components: 12
                learning_method: online
                batch_size: 512
                learning_offset: 9
                learning_decay: 0.7
                doc_topic_prior: 1
        transcript_score:
            grid_score:
                hex_width: 12
                offset_steps: [-1, 0, 1]
                step_size: 6
            plot_filter:
                min_transcripts_per_hex: 5
                max_transcripts_per_hex: 50
        plot:
            microns_per_inch: 50
            palette: Spectral
            background: black
            plot_top_n_factors: 12
    resources:
        big:
            mem: "64G"
            cpu: 8
            time: "24:00:00"
        ram:
            mem: "16G"
            cpu: 2
            time: "04:00:00"