
# Update default config with runtime config
configfile: os.path.join(workflow.basedir, "../", "config", "config.yaml")
configfile: os.path.join(workflow.basedir, "../", "config", "system_config.yaml")
config.update(config["spers"])
config.update(config["spers"]["ficture"])


# Samples processed together (one shared model, per-sample outputs)
SAMPLES = list(config["args"]["samples"].keys())


# Keep sample wildcards from greedily eating path separators
wildcard_constraints:
    sample = r"[^/]+"


# Rules files
include: os.path.join(workflow.basedir, "rules", "preflight.smk")
include: os.path.join(workflow.basedir, "rules", "preprocessing.smk")
include: os.path.join(workflow.basedir, "rules", "generate_lda_model.smk")
include: os.path.join(workflow.basedir, "rules", "transcript_score.smk")


# Target rules
@targetRule
rule all:
    input:
        targets.values()


@targetRule
rule print_targets:
    run:
        print("\nTop level rules are: \n", file=sys.stderr)
        print("* " + "\n* ".join(target_rules) + "\n\n", file=sys.stderr)
