spers:
    ficture:
        cosmx:
            mu_scale: 10
            headers:
                X: x_global_px
                Y: y_global_px
                gene: target
        xenium:
            mu_scale: 1
            headers:
                X: x_location
                Y: y_location
                gene: feature_name
        preprocessing:
            batch_size: 500
            batch_buff: 30
    resources:
        big:
            mem: 64000
            cpu: 32
            time: "24:00:00"
        med:
            mem: 16000
            cpu: 8
            time: "04:00:00"
        sml:
            mem: 2000
            cpu: 1
            time: "01:00:00"
        ram:
            mem: 16000
            cpu: 2
            time: "04:00:00"